Repository trs/star-search, pull requests merged in 2020-10, with the labels that each got.

#3 remove tailwind
  README.md
  components/Repository.js
  package-lock.json
  package.json
  pages/_app.js
  pages/auth/login.js
  pages/auth/logout.js
  pages/index.js
  postcss.config.js
  styles/globals.css
  styles/tailwind.css
  tailwind.config.js
Labels: hacktoberfest, hacktoberfest-accepted

#4 Made login and logout buttons more obviously clickable
  pages/login.js
  pages/logout.js
Labels: hacktoberfest-accepted

#5 Improve button look, more "clickable"
  components/Button.js
  components/Button.module.css
  pages/login.js
  pages/logout.js
Labels: enhancement
